apiVersion: apps/v1
kind: Deployment
metadata:
  name: gitops-app-deployment
spec:
  revisionHistoryLimit: 2
  strategy:
    type: RollingUpdate
  selector:
    matchLabels:
      app: gitOps-app
  template:
    metadata:
      annotations:
        checksum: "1"
    spec:
      containers:
        - name: core
          imagePullPolicy: Always
          image: "oluwatunmiseolat/gitops-eks:latest"
          envFrom:
            - secretRef:
                name: "gitops-app-secret"
          ports:
            - name: http
              containerPort: 3400
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /health
              port: 3400
            initialDelaySeconds: 30
            periodSeconds: 10