# https://external-secrets.io/latest/introduction/getting-started/
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: gitops-app-eso
spec:
  refreshInterval: 2m
  secretStoreRef:
    name: gitops-app-secrets-store
    kind: SecretStore
  target:
    name: gitops-app-eso-secret
    creationPolicy: Owner
  data:
    - secretKey: APP_NAME
      remoteRef:
        key: GitOpsApp
        property: APP_NAME
    - secretKey: NODE_ENV
      remoteRef:
        key: GitOpsApp
        property: NODE_ENV