# https://dev.to/thenjdevopsguy/getting-started-with-kustomize-for-kubernetes-32nh
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - deployment.yaml
  - service.yaml
  - ingress.yaml
  - hpa.yaml
  - secret-provider-class.yaml
  - external-secret.yaml
  - secret-store.yaml
  # - service-account.yaml # Excluded because role arn in annotation is redacted

commonLabels:
  app: gitops-app

images:
  - name: "oluwatunmiseolat/gitops-eks"
    newTag: "6a7a665"
