apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - deployment.yaml
  - service.yaml
  - ingress.yaml
  - hpa.yaml
  - secret-provider-class.yaml

commonLabels:
  app: gitOps-app
  environment: production

images:
  - name: ""
    newTag: latest

# Added this to force deployment retrigger 🙂
patches:
  - target:
      kind: Deployment
      name: "" 
    patch: |-
      - op: add
        path: /spec/template/metadata/annotations/checksum
        value: ""