# https://dev.to/thenjdevopsguy/getting-started-with-kustomize-for-kubernetes-32nh
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - deployment.yaml
  - service.yaml
  - hpa.yaml
  - external-secret.yaml
  - secret-store.yaml
  - secret-provider-class.yaml
   # Excluded because role arn in annotation is redacted
  # - ingress.yaml
  # - service-account.yaml

commonLabels:
  app: gitops-app

images:
  - name: "oluwatunmiseolat/gitops-eks"
    newTag: "b13b865"
