# Specifies how to connect to the external secret management provider
apiVersion: external-secrets.io/v1beta1
kind: SecretStore
metadata:
  name: gitops-app-secrets-store
spec:
  provider: 
    aws:
      service: SecretsManager
      region: eu-central-1
      auth:
        jwt:
          serviceAccountRef:
            name: gitops-app-sa